### PR TITLE
fix: CI and dependency updates

### LINKED ISSUE #18: fast-multilingual-e5-large.tar.gz Access denied
Hello, 
I want to use fast-multilingual-e5-large, but when the lib is trying to download it I get:

```
An error occurred: Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/tar/lib/warn-mixin.js:21:40)
    at Unpack.warn (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/tar/lib/unpack.js:236:18)
    at Unpack.<anonymous> (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/tar/lib/parse.js:83:14)
    at Unpack.emit (node:events:526:35)
    at [emit] (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/tar/lib/parse.js:313:12)
    at [maybeEnd] (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/tar/lib/parse.js:468:17)
    at [consumeChunk] (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/tar/lib/parse.js:500:21)
    at Unpack.write (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/tar/lib/parse.js:427:25)
    at Unpack.end (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/tar/lib/parse.js:548:14)
    at Pipe.end (/Users/vladislavsorokin/Projects/tax-chatbot/node_modules/minipass/index.js:75:17) {
  recoverable: false,
  file: 'local_cache/fast-multilingual-e5-large.tar.gz',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
```

then when I click on fast-multilingual-e5-large.tar.gz I see the file with content:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details></Error>
```

### LINKED ISSUE #24: Update onnxruntime-node dep
Can we get updates to this package for the deps? e.g onnxruntime-node to 1.20.1?
Or is fastembed-js on minimal support atm?

### PR DESCRIPTION
**Pull request by smorimoto**
Closes #24 
Closes #18

- Run `sort-package-json`
- Enable `declarationMap` and `sourceMap` in `tsconfig.json`
- Fix `publint` errors
- Bump `onnxruntime-node` to 1.21.0
- Fix tests
- Fix GitHub Actions workflows

### CODE REVIEW

File: src/fastembed.ts [hunk 1]
```diff
@@ -127,7 +127,13 @@ export class FlagEmbedding extends Embedding {
...
     const tokenizer = this.loadTokenizer(modelDir, maxLength);
 
-    const modelPath = path.join(modelDir.toString(), "model_optimized.onnx");
+    const modelPath = path.join(
+      modelDir.toString(),
+      model === EmbeddingModel.MLE5Large ||
+        model === EmbeddingModel.AllMiniLML6V2
+        ? "model.onnx"
+        : "model_optimized.onnx",
+    );
```
Comment (smorimoto) [inline src/fastembed.ts:136]: I have to admit that this is not a very clean implementation, but it's still simple enough.

File: .github/workflows/compliance.yml [hunk 2]
```diff
@@ -1,7 +1,7 @@
 name: "PR Compliance"
 
 on:
-  pull_request_target:
```
Comment (smorimoto) [inline .github/workflows/compliance.yml:4]: I don't know why you use `pull_request_target`, but it does **_not_** actually run test for the contents of PR...

**Comment by smorimoto** [comment]
@Anush008 [Mastra](https://github.com/mastra-ai/mastra) uses this package internally, but due to the outdated version of `onnxruntime-node`, some CI/CD providers are encountering build errors related to `node-gyp`. I'm currently forcibly circumventing this by using Yarn's [resolutions](https://yarnpkg.com/configuration/manifest#resolutions), but this workaround isn't an obvious escape hatch for most users.

**Comment by smorimoto** [comment]
Hmm, I guess I have to fix how to use tar

File: .github/workflows/compliance.yml (hunk 2 above)
Comment (Anush008) [reply .github/workflows/compliance.yml:4]: Thanks. This was an oversight.

**Comment by smorimoto** [comment]
OK - for now I've reverted the commit that bumped the tar version.

**Comment by smorimoto** [comment]
I don't know why compliance is failing, but all issues in the scope of this PR have been fixed!

**Review by Anush008 — APPROVED** [review]
LGTM! Thanks for taking the time to contribute @.

**Comment by smorimoto** [comment]
Likewise!
